version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  local_elasticsearch_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: language_acts_local_django
    depends_on:
      - postgres
      - elasticsearch
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start
    restart: unless-stopped

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: language_acts_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:7.10.1
    volumes:
      - local_elasticsearch_data:/usr/share/elasticsearch/data
    env_file:
      - ./.envs/.local/.elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
    restart: unless-stopped

#  kibana:
#    image: kibana:7.5.1
#    depends_on:
#      - elasticsearch
#    #env_file:
#    #  - ./.envs/.local/.kibana
#    ports:
#      - '5601:5601'
#    restart: unless-stopped
