#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset




if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi
export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

postgres_ready() {
python << END
import sys

import psycopg2

try:
    psycopg2.connect(
        dbname="${POSTGRES_DB}",
        user="${POSTGRES_USER}",
        password="${POSTGRES_PASSWORD}",
        host="${POSTGRES_HOST}",
        port="${POSTGRES_PORT}",
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}
until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'

if [ -z "${DEFAULT_ELASTICSEARCH_CONNECTION}" ]; then
    export DEFAULT_ELASTICSEARCH_CONNECTION="http://elasticsearch:9200"
fi

elastic_ready() {
python << END
import sys

from elasticsearch_dsl import Search
from elasticsearch_dsl import connections
from elasticsearch import Elasticsearch

try:
    es = Elasticsearch(['http://localhost:9200/'], verify_certs=True)
    es.ping()
except elasticsearch.exceptions.ConnectionError:
    sys.exit(-1)
sys.exit(0)

END
}
until elastic_ready; do
  >&2 echo 'Waiting for Elasticsearch to become available...'
  sleep 1
done
>&2 echo 'Elasticsearch is available'


exec "$@"
