# Generated by Django 2.2.10 on 2020-10-01 11:19

import cms.models.streamfield
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cms', '0062_rich_text_captions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField(
                [
                    ('home', wagtail.core.blocks.StructBlock(
                        [('url', wagtail.core.blocks.URLBlock(required=False)),
                         (
                             'page',
                             wagtail.core.blocks.PageChooserBlock(
                                 required=False)),
                         ('title', wagtail.core.blocks.CharBlock()),
                         ('description', wagtail.core.blocks.RichTextBlock())],
                        icon='grip', label='Homepage Block')
                     ), ('h2',
                         wagtail.core.blocks.CharBlock(
                             classname='title',
                             icon='title')),
                    ('h3', wagtail.core.blocks.CharBlock(classname='title',
                                                         icon='title')
                     ), ('h4',
                         wagtail.core.blocks.CharBlock(
                             classname='title',
                             icon='title')),
                    ('h5', wagtail.core.blocks.CharBlock(classname='title',
                                                         icon='title')),
                    ('intro',
                     wagtail.core.blocks.RichTextBlock(icon='pilcrow')
                     ), ('paragraph',
                         wagtail.core.blocks.RichTextBlock(icon='pilcrow')
                         ),
                    ('pullquote', wagtail.core.blocks.StructBlock([
                        ('quote', wagtail.core.blocks.TextBlock('quote title')
                         ),
                        ('attribution', wagtail.core.blocks.CharBlock()), (
                            'affiliation',
                            wagtail.core.blocks.CharBlock(required=False)),
                        ('style',
                         cms.models.streamfield.PullQuoteStyleChoiceBlock())
                    ], icon='openquote')
                     ), ('image',
                         wagtail.core.blocks.StructBlock(
                             [(
                                 'image',
                                 (wagtail.images.
                                  blocks.ImageChooserBlock())
                             ),
                                 (
                                     'caption',
                                     wagtail.core.blocks.RichTextBlock(
                                         required=False)
                                 ),
                                 (
                                     'alignment',
                                     (cms.models.streamfield.
                                      ImageFormatChoiceBlock())
                                 ),
                                 (
                                     'text',
                                     wagtail.core.blocks.RichTextBlock(
                                         required=False))
                             ], icon='image',
                             label='Aligned image + '
                                   'text')),
                    ('grid', wagtail.core.blocks.StructBlock(
                        [('image_block',
                          wagtail.core.blocks.ListBlock(
                              wagtail.core.blocks.StructBlock(
                                  [(
                                      'image',
                                      wagtail.images.blocks.ImageChooserBlock()
                                  ),
                                      (
                                          'link',
                                          wagtail.core.blocks.URLBlock(
                                              required=False)),
                                      (
                                          'text',
                                          wagtail.core.blocks.CharBlock(
                                              required=False))]),
                              required=False))],
                        icon='grip',
                        label='Image '
                              'grid')),
                    ('document', wagtail.documents.blocks.DocumentChooserBlock(
                        icon='doc-full-inverse')
                     ), ('link',
                         wagtail.core.blocks.StructBlock(
                             [('url',
                               wagtail.core.blocks.URLBlock(
                                   required=False)),
                              (
                                  'page',
                                  wagtail.core.blocks.PageChooserBlock(
                                      required=False)),
                              (
                                  'label',
                                  wagtail.core.blocks.CharBlock()),
                              ('style',
                               cms.models.streamfield.LinkStyleChoiceBlock())],
                             icon='link')),
                    ('embed', wagtail.embeds.blocks.EmbedBlock(icon='media')),
                    (
                        'html', wagtail.core.blocks.StructBlock(
                            [('html', wagtail.core.blocks.RawHTMLBlock()), (
                                'alignment',
                                (cms.models.
                                 streamfield.HTMLAlignmentChoiceBlock()))],
                            icon='code', label='Raw HTML')
                    ), ('d3',
                        wagtail.core.blocks.StructBlock(
                            [('html',
                              wagtail.core.blocks.RawHTMLBlock(
                                  required=False)),
                             ('css',
                              wagtail.core.blocks.RawHTMLBlock(
                                  required=False)),
                             ('js',
                              wagtail.core.blocks.RawHTMLBlock(
                                  required=False)),
                             (
                                 'additional_files',
                                 wagtail.core.blocks.RawHTMLBlock(
                                     required=False,
                                     verbose_name='Additional JS             '
                                                  '                       '
                                                  'files to load.'))],
                            icon='media',
                            label='D3 '
                                  'Visualisation')),
                    ('table', wagtail.contrib.table_block.blocks.TableBlock()),
                    (
                        'carousel', wagtail.core.blocks.StreamBlock(
                            [('slides',
                              wagtail.core.blocks.StructBlock(
                                  [(
                                      'title',
                                      wagtail.core.blocks.RichTextBlock(
                                          editor='carousel',
                                          required=True)),
                                      (
                                          'heading',
                                          wagtail.core.blocks.RichTextBlock(
                                              default='',
                                              editor='carousel',
                                              label='Section heading',
                                              required=False)),
                                      (
                                          'description',
                                          wagtail.core.blocks.RichTextBlock(
                                              required=False)),
                                      (
                                          'url',
                                          wagtail.core.blocks.URLBlock(
                                              required=False)),
                                      (
                                          'page',
                                          wagtail.core.blocks.PageChooserBlock(
                                              help_text='Overrides url',
                                              required=False)),
                                      (
                                          'image',
                                          (wagtail.images.blocks.
                                           ImageChooserBlock(required=True))
                                      ),
                                      (
                                          'caption',
                                          wagtail.core.blocks.RichTextBlock(
                                              editor='carousel',
                                              label='Image caption',
                                              required=False))],
                                  icon='image',
                                  label='Slide')),
                             (
                                 'blog_slide',
                                 wagtail.core.blocks.StructBlock(
                                     [(
                                         'page',
                                         wagtail.core.blocks.PageChooserBlock(
                                             page_type=[
                                                 'cms.BlogPost'],
                                             required=False)),
                                         (
                                             'caption',
                                             wagtail.core.blocks.RichTextBlock(
                                                 editor='carousel',
                                                 required=False)),
                                         (
                                             'heading',
                                             wagtail.core.blocks.RichTextBlock(
                                                 default='Blog',
                                                 editor='carousel',
                                                 required=False))],
                                     icon='edit',
                                     label='Blog slide')),
                             (
                                 'latest_news',
                                 cms.models.pages.LatestNewsSlideBlock()),
                             (
                                 'latest_post',
                                 cms.models.pages.LatestBlogSlideBlock()),
                             (
                                 'next_event',
                                 cms.models.pages.UpcomingEventSlideBlock()),
                             (
                                 'event_slide',
                                 wagtail.core.blocks.StructBlock(
                                     [(
                                         'page',
                                         wagtail.core.blocks.PageChooserBlock(
                                             page_type=[
                                                 'cms.Event'],
                                             required=True)),
                                         (
                                             'caption',
                                             wagtail.core.blocks.RichTextBlock(
                                                 editor='carousel',
                                                 required=False)),
                                         (
                                             'heading',
                                             wagtail.core.blocks.RichTextBlock(
                                                 default='Event',
                                                 editor='carousel',
                                                 required=False))],
                                     icon='date',
                                     label='Event slide')),
                             (
                                 'news_slide',
                                 wagtail.core.blocks.StructBlock(
                                     [(
                                         'page',
                                         wagtail.core.blocks.PageChooserBlock(
                                             page_type=[
                                                 'cms.NewsPost'],
                                             required=False)),
                                         (
                                             'caption',
                                             wagtail.core.blocks.RichTextBlock(
                                                 editor='carousel',
                                                 required=False)),
                                         (
                                             'heading',
                                             wagtail.core.blocks.RichTextBlock(
                                                 default='News',
                                                 editor='carousel',
                                                 required=False))],
                                     icon='edit',
                                     label='News slide'))]))]),
        ),
    ]
