# Generated by Django 2.2.10 on 2020-10-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cms', '0063_rich_text_headings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibliographyEntry',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('publisher', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Glossary term',
                'verbose_name_plural': 'Glossary terms',
            },
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('term', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Glossary term',
                'verbose_name_plural': 'Glossary terms',
            },
        ),
    ]
