# Generated by Django 2.2.10 on 2020-10-14 13:39

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('cms', '0064_bibliographyentry_glossaryterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='GlossaryTermItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('glossary_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cms.GlossaryTerm')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='glossary_terms', to='cms.GlossaryPage')),
            ],
            options={
                'verbose_name': 'Glossary item',
                'verbose_name_plural': 'Glossary items',
            },
        ),
    ]
