# Generated by Django 2.2.10 on 2020-10-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cms', '0066_bibliographyentryitem_bibliographypage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibliographyentry',
            options={'verbose_name': 'Bibliography entry',
                     'verbose_name_plural': 'Bibliography entries'},
        ),
        migrations.AddField(
            model_name='bibliographyentry',
            name='reference',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
