# Generated by Django 3.0.10 on 2020-11-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0067_bibliography_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bibliographyentry',
            old_name='author',
            new_name='author_surname',
        ),
        migrations.AddField(
            model_name='bibliographyentry',
            name='author_firstame',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='bibliographyentry',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
