# Generated by Django 3.0.10 on 2020-11-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0069_auto_20201109_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliographyentry',
            name='publication_year',
            field=models.IntegerField(default=0),
        ),
    ]
