# Generated by Django 3.0.10 on 2021-02-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0070_bibliographyentry_publication_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bibliographyentry',
            name='author_firstname',
        ),
        migrations.RemoveField(
            model_name='bibliographyentry',
            name='author_surname',
        ),
        migrations.RemoveField(
            model_name='bibliographyentry',
            name='publication_year',
        ),
        migrations.RemoveField(
            model_name='bibliographyentry',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='bibliographyentry',
            name='title',
        ),
        migrations.AddField(
            model_name='bibliographyentry',
            name='full_citation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
