# Generated by Django 3.0.10 on 2021-03-09 13:50

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0072_record_entry_streamblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliographyentry',
            name='reference',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
