# Generated by Django 3.0.10 on 2021-03-09 13:54

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0073_bibliography_richtextfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliographyentry',
            name='full_citation',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
