# Generated by Django 3.0.10 on 2021-04-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0074_bibliography_citation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibliographyentry',
            options={'ordering': ['full_citation'], 'verbose_name': 'Bibliography entry', 'verbose_name_plural': 'Bibliography entries'},
        ),
        migrations.AlterModelOptions(
            name='glossaryterm',
            options={'ordering': ['term'], 'verbose_name': 'Glossary term', 'verbose_name_plural': 'Glossary terms'},
        ),
    ]
