# Generated by Django 3.0.10 on 2021-04-14 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0076_bibliography_orderable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossarytermitem',
            options={'ordering': ['glossary_term'], 'verbose_name': 'Glossary item', 'verbose_name_plural': 'Glossary items'},
        ),
        migrations.RemoveField(
            model_name='glossarytermitem',
            name='sort_order',
        ),
    ]
