# Generated by Django 3.0.10 on 2021-05-17 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0079_term_raw'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossarytermitem',
            options={'ordering': ['glossary_term__term_raw'], 'verbose_name': 'Glossary item', 'verbose_name_plural': 'Glossary items'},
        ),
    ]
