# Generated by Django 3.0.10 on 2021-05-18 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0081_glossarytermitem_raw'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibliographyentry',
            options={'ordering': ['reference'], 'verbose_name': 'Bibliography entry', 'verbose_name_plural': 'Bibliography entries'},
        ),
        migrations.AlterModelOptions(
            name='glossarytermitem',
            options={'ordering': ['glossary_term'], 'verbose_name': 'Glossary item', 'verbose_name_plural': 'Glossary items'},
        ),
        migrations.RemoveField(
            model_name='glossarytermitem',
            name='term_raw',
        ),
    ]
